print("Hello!, Muhammad Amir Awan")
print("Nice to meet you")
print("You are a good student and quick learner")
print("I am very enthusiastic about learning AI.")
print("I am a Banker by profession")
print("I am looking forward to applying AI in finance.")
print("I believe AI can help in making better financial decisions.")
print("I am eager to explore the various applications of AI in banking.")
print("I rarely feel frustrated when I encounter complex problems.")
print("I am confident that I can overcome any challenges that come my way.")
print("I am committed to continuous learning and improvement.")