print("Welcome to AI Genius Class")
print("My Name is Muhammad Amir Awan")
print("I am your student for this course.")
print("Let's start our journey into the world of AI!")
print("I am excited to learn and grow in this field.")
print("I am very smart and multitasking student")
print("I am a quick learner.")
print("I am a Banker by my profession")
print("I am looking forward to applying AI in finance.")
print("I believe AI can help in making better financial decisions.")
print("I am eager to explore the various applications of AI in banking.")
print("I rarely feel frustrated when I encounter complex problems.")
print("I am confident that I can overcome any challenges that come my way.")
print("I am committed to continuous learning and improvement.")