import numpy as np
# a = np.array([1, 2, 3])
# print(a)

# a1 = np.mean([1, 2, 3])
# print(a1)

# a2 = np.median([4, 5, 6])
# print(a2)
# a = np.array(["name, age, marks"])
# name = input("Enter your Name: ")
# age = int(input("Enter your Age: "))
# marks = int(input("Enter your Marks: "))
# stu_1 = np.array([name, age, marks])
# print(stu_1)
# name = input("Enter your Name: ")
# age = int(input("Enter your Age: "))
# marks = int(input("Enter your Marks: "))
# stu_2 = np.array([name, age, marks])
# print(stu_2)
# name = input("Enter your Name: ")
# age = int(input("Enter your Age: "))
# marks = int(input("Enter your Marks: "))
# stu_3 = np.array([name, age, marks])
# print(stu_3)
# name = input("Enter your Name: ")
# age = int(input("Enter your Age: "))
# marks = int(input("Enter your Marks: "))
# stu_4 = np.array([name, age, marks])
# print(stu_4)
# name = input("Enter your Name: ")
# age = int(input("Enter your Age: "))
# marks = int(input("Enter your Marks: "))
# stu_5 = np.array([name, age, marks])
# print(stu_5)

# def student_info():
#     name = input("Enter your Name: ")
#     age = int(input("Enter your Age: "))
#     marks = int(input("Enter your Marks: "))
# def show_info(a, name, age, marks):
#     print("Name: ", name)
#     print("Age: ", age)
#     print("Marks: ", marks)
# student_info()

# a1=np.array([1, 2, 3, 4, 5])
# min=np.min(a1)
# print(min)
# max=np.max(a1)
# print(max)
# arrange=np.arange(1, 5, 2)
# print(arrange)
# minrange=np.argmin(a1)
# print(minrange)
# maxrange=np.argmax(a1)
# print(maxrange)
# # reshape=np.reshape(a1, (2,2))
# # print(reshape)
# reshape=np.reshape(a1, (1,5))
# print(reshape)
# size=np.size(a1)
# print(size)
# arr1=np.array([1,2,3,4,5])
# print(arr1.dtype)
# dinfo=np.info(a1)
# print(dinfo)

# 2D Array
# arr2=np.array([[1, 2, 3], [4, 5, 6]])
# print(arr2)
# print(arr2.shape)
# reshape=np.reshape(arr2, (3,2))
# print(reshape)
# print(reshape.shape)

# amir = np.array([50,60,70,80,90])
# ali = np.array([40,50,60,70,80])
# ahsan = np.array([30,40,50,60,70])
# noor = np.array([20,30,40,50,60])
# pari = np.array([10,20,30,40,50])
# mean_amir=np.mean(amir)
# print(mean_amir)
# median_amir=np.median(amir)
# print(median_amir)
# min=np.min(amir)
# print(min)
# max=np.max(amir)
# print(amir)
# minrange=np.argmin(amir)
# print(minrange)
# maxrange=np.argmax(amir)
# print(maxrange)
# mean_ali=np.mean(ali)
# print(mean_ali)
# median_ali=np.median(ali)
# print(median_ali)
# min=np.min(ali)
# print(min)
# max=np.max(ali)
# print(ali)
# minrange=np.argmin(ali)
# print(minrange)
# maxrange=np.argmax(ali)
# print(maxrange)
# addition_amir=np.sum(amir)
# print(addition_amir)
# subtraction_amir=np.subtract(amir, ali)
# print(subtraction_amir)
# multiplication_amir=np.multiply(amir, ali)
# print(multiplication_amir)
# division_amir=np.divide(amir, ali)
# print(division_amir)
# exponential_amir=np.exp(amir)
# print(exponential_amir)

# a = np.array([[1, 2, 3], [4, 5, 6]])
# print(a)
# square_root = np.sqrt(a)
# print(square_root)
# exponential = np.exp(a)
# print(exponential)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
square_root = np.sqrt(a)
print(square_root)
exponential = np.exp(a)
print(exponential)
addition = np.add(a,b)
print(addition)
# addition_1 = np.sum(a,b)
# print(addition_1)
subtraction = np.subtract(a, b)
print(subtraction)
subtraction_1 = np.subtract(b, a)
print(subtraction_1)
multiplication = np.multiply(a, b)
print(multiplication)
division = np.divide(a, b)
print(division)
exponential = np.exp(a*b)
print(exponential)
c = a+b
print(c)
d = a-b
print(d)
e = a*b
print(e)
f = a/b
print(f)